use fst::Map;
use lazy_static::lazy_static;
use std::{os::unix::ffi::OsStrExt, path::Path};

lazy_static! {
    static ref FILENAME_ICONS: Map<&'static [u8]> = {
        const FILENAME_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/filename_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FILENAME_ICONS_BYTES).unwrap_unchecked() }
    };
    static ref EXT_ICONS: Map<&'static [u8]> = {
        const EXT_ICONS_BYTES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/ext_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe {
            Map::new(EXT_ICONS_BYTES).unwrap_unchecked()
        }
    };
    static ref FOLDER_ICONS: Map<&'static [u8]> = {
        const FOLDER_ICONS_BYTES: &[u8] =
            include_bytes!(concat!(env!("OUT_DIR"), "/folder_icons.bin"));

        // Safety: the bytes are correctly generated by fst in the build script, so we can use `unwrap_unchecked`
        unsafe { Map::new(FOLDER_ICONS_BYTES).unwrap_unchecked() }
    };
}

#[derive(thiserror::Error, Debug, PartialEq)]
pub enum IconError {
    #[error("User provided invalid path")]
    InvalidPath,
    #[error("Icon for {0} not found")]
    IconNotFound(String),
}

pub fn get_icon_for_file(path: impl AsRef<Path>) -> Result<u64, IconError> {
    let path = path.as_ref();
    let basename = path.file_name().ok_or(IconError::InvalidPath)?;

    FILENAME_ICONS
        .get(basename.as_bytes())
        .or_else(|| {
            path.extension()
                .and_then(|ext| EXT_ICONS.get(ext.as_bytes()))
        })
        .ok_or(IconError::IconNotFound(
            path.to_str().unwrap_or("unparsable path").to_string(),
        ))
}

pub fn get_icon_for_folder(path: impl AsRef<Path>) -> Result<u64, IconError> {
    let path = path.as_ref();
    let basename = path.file_name().ok_or(IconError::InvalidPath)?;

    FOLDER_ICONS
        .get(basename.as_bytes())
        .ok_or(IconError::IconNotFound(
            path.to_str().unwrap_or("unparsable path").to_string(),
        ))
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn common_languages() {
        assert_eq!(get_icon_for_file("./test.js"), Ok(296));
        assert_eq!(get_icon_for_file("./test.ts"), Ok(633));
        assert_eq!(get_icon_for_file("./test.jsx"), Ok(508));
        assert_eq!(get_icon_for_file("./test.tsx"), Ok(529));
        assert_eq!(get_icon_for_file("./test.json"), Ok(284));
        assert_eq!(get_icon_for_file("./test.yaml"), Ok(708));
        assert_eq!(get_icon_for_file("./test.yml"), Ok(708));
        assert_eq!(get_icon_for_file("./test.md"), Ok(361));
        assert_eq!(get_icon_for_file("./test.css"), Ok(116));
        assert_eq!(get_icon_for_file("./test.html"), Ok(255));
        assert_eq!(get_icon_for_file("./test.rs"), Ok(525));
    }

    #[test]
    fn common_folders() {
        assert_eq!(get_icon_for_folder("./.github"), Ok(862));
        assert_eq!(get_icon_for_folder("./src"), Ok(1054));
        assert_eq!(get_icon_for_folder("./tests"), Ok(1084));
    }
}
